apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-shopping-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-shopping-site
  template:
    metadata:
      labels:
        app: k8s-shopping-site
    spec:
      containers:
      - name: k8s-shopping-site
        image: your-dockerhub-username/k8s-shopping-site:latest # 替換為你的 Docker 映像
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-shopping-site
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: k8s-shopping-site
